sources:
- name: raw_customers
  path: "'data/customers.csv'"
- name: raw_orders
  path: "'data/orders.csv'"
- name: raw_payments
  path: "'data/payments.csv'"
models:
- name: stg_customers
  columns:
  - name: customer_id
    tests:
    - type: unique
    - type: not_null
- name: stg_orders
  columns:
  - name: order_id
    tests:
    - type: unique
    - type: not_null
  - name: status
    tests:
    - type: accepted_values
      info:
        values: placed,shipped,completed,return_pending,returned
- name: stg_payments
  columns:
  - name: payment_id
    tests:
    - type: unique
    - type: not_null
  - name: payment_method
    tests:
    - type: accepted_values
      info:
        values: credit_card,coupon,bank_transfer,gift_card
